#!/usr/bin/env bash
# Downstream conformance gate: run the LimniFS test suite against the
# CURRENT omnizip-rs workspace.
#
# Why this exists: every LimniFS validation pass has caught omnizip
# regressions our own suites missed (#388 MATCH_LEN_CAP CI hang, #408
# the uncapped-default repeat). Their whole-file drop tests exercise
# content classes and timing envelopes our unit tests don't. This
# harness makes their suite OUR gate: a clone at the pinned ref, with
# every omnizip-* dependency patched to this workspace, runs the full
# LimniFS test suite. If it fails here, it fails before shipping.
#
# Usage: tests/downstream/run.sh [workspace-dir]
#   workspace-dir defaults to the repo root this script lives in.
#
# The pin lives in limnifs-ref.txt (same convention as the Ruby
# differential harness). Bump it deliberately: a new pin should come
# with a note about what changed downstream.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
WORKSPACE="${1:-$ROOT}"
# LIMNIFS_REF overrides the pin (the canary runs against main).
REF="${LIMNIFS_REF:-$(cat "$ROOT/tests/downstream/limnifs-ref.txt")}"
REPO="https://github.com/limnifs/limnifs.git"
CLONE="${CLONE_DIR:-$(mktemp -d "${TMPDIR:-/tmp}/omnizip-downstream-XXXXXX")}"

echo "==> cloning limnifs @ $REF into $CLONE"
git clone --quiet "$REPO" "$CLONE"
git -C "$CLONE" checkout --quiet "$REF"

echo "==> patching omnizip deps to this workspace ($WORKSPACE)"
mkdir -p "$CLONE/.cargo"
CARGO_PATCH="$CLONE/.cargo/config.toml"
{
    echo "# Generated by omnizip-rs tests/downstream/run.sh — do not edit."
    echo "[patch.crates-io]"
    for dir in "$WORKSPACE"/omnizip-*/; do
        name="$(basename "$dir")"
        # Only patch crates LimniFS actually depends on; patching
        # extras is harmless but noisy in cargo's resolution output.
        echo "$name = { path = \"$dir\" }"
    done
} > "$CARGO_PATCH"
cat "$CARGO_PATCH"

echo "==> running the LimniFS suite (release, full workspace)"
cd "$CLONE"
# Their slowest suites take ~4 minutes each; the CI job's timeout
# bounds the pathological-hang class this gate exists to catch.
cargo test --release --workspace

echo "==> downstream gate PASSED at limnifs@$REF"
