//! Probability prices — port of xz's `rangecoder/price.h` +
//! `price_table.c`. Prices are in 1/8-bit units.
#![forbid(unsafe_code)]

use crate::bit_model::BitModel;
use crate::constants::BIT_MODEL_TOTAL;

const RC_MOVE_REDUCING_BITS: u32 = 4;
const RC_BIT_PRICE_SHIFT_BITS: u32 = 4;
const RC_PRICE_TABLE_SIZE: usize = (BIT_MODEL_TOTAL as usize) >> RC_MOVE_REDUCING_BITS;

/// `lzma_rc_prices` from price_table.c (generated by price_tablegen.c).
#[rustfmt::skip]
const LZMA_RC_PRICES: [u8; RC_PRICE_TABLE_SIZE] = [
	128, 103,  91,  84,  78,  73,  69,  66,
	 63,  61,  58,  56,  54,  52,  51,  49,
	 48,  46,  45,  44,  43,  42,  41,  40,
	 39,  38,  37,  36,  35,  34,  34,  33,
	 32,  31,  31,  30,  29,  29,  28,  28,
	 27,  26,  26,  25,  25,  24,  24,  23,
	 23,  22,  22,  22,  21,  21,  20,  20,
	 19,  19,  19,  18,  18,  17,  17,  17,
	 16,  16,  16,  15,  15,  15,  14,  14,
	 14,  13,  13,  13,  12,  12,  12,  11,
	 11,  11,  11,  10,  10,  10,  10,   9,
	  9,   9,   9,   8,   8,   8,   8,   7,
	  7,   7,   7,   6,   6,   6,   6,   5,
	  5,   5,   5,   5,   4,   4,   4,   4,
	  3,   3,   3,   3,   3,   2,   2,   2,
	  2,   2,   2,   1,   1,   1,   1,   1,
];

/// Price of encoding `bit` through a model at `probability`.
#[must_use]
pub fn rc_bit_price(probability: u16, bit: u32) -> u32 {
    let index = (probability ^ ((0u16.wrapping_sub(bit as u16)) & (BIT_MODEL_TOTAL - 1)))
        >> RC_MOVE_REDUCING_BITS;
    u32::from(LZMA_RC_PRICES[index as usize])
}

/// Price of encoding a 0 bit.
#[must_use]
pub fn rc_bit_0_price(probability: u16) -> u32 {
    u32::from(LZMA_RC_PRICES[(probability >> RC_MOVE_REDUCING_BITS) as usize])
}

/// Price of encoding a 1 bit.
#[must_use]
pub fn rc_bit_1_price(probability: u16) -> u32 {
    u32::from(
        LZMA_RC_PRICES[((probability ^ (BIT_MODEL_TOTAL - 1)) >> RC_MOVE_REDUCING_BITS) as usize],
    )
}

/// Price of a bit-tree-encoded symbol (top-down, MSB first).
#[must_use]
pub fn rc_bittree_price(probs: &[BitModel], bit_levels: u32, symbol: u32) -> u32 {
    let mut price = 0u32;
    let mut symbol = symbol + (1u32 << bit_levels);
    loop {
        let bit = symbol & 1;
        symbol >>= 1;
        price += rc_bit_price(
            probs[usize::try_from(symbol).unwrap_or(0)].probability(),
            bit,
        );
        if symbol == 1 {
            break;
        }
    }
    price
}

/// Price of a reverse bit-tree-encoded symbol (LSB first).
#[must_use]
pub fn rc_bittree_reverse_price(probs: &[BitModel], bit_levels: u32, symbol: u32) -> u32 {
    let mut price = 0u32;
    let mut symbol = symbol;
    let mut model_index = 1u32;
    let mut remaining = bit_levels;
    loop {
        let bit = symbol & 1;
        symbol >>= 1;
        price += rc_bit_price(
            probs[usize::try_from(model_index).unwrap_or(0)].probability(),
            bit,
        );
        model_index = (model_index << 1) + bit;
        remaining -= 1;
        if remaining == 0 {
            break;
        }
    }
    price
}

/// Price of `bits` direct bits.
#[must_use]
pub fn rc_direct_price(bits: u32) -> u32 {
    bits << RC_BIT_PRICE_SHIFT_BITS
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn balanced_bit_costs_about_half_bit() {
        assert_eq!(rc_bit_0_price(1024), 16);
        assert_eq!(rc_bit_1_price(1024), 17); // u8 table rounding
    }

    #[test]
    fn table_extremes() {
        assert_eq!(rc_bit_0_price(1), 128); // near-impossible 0: ~16 bits
        assert_eq!(rc_bit_1_price(2047), 128);
    }
}
